apiVersion: v1
kind: Service
metadata:
 name: currency-conversion-service
 labels:
  app: currency-conversion-service
spec:
 ports:
 - port: 9100
   protocol: TCP
 selector:
  app: currency-conversion-service
 type: NodePort
