spring:
 application:
  name: spring-config-server
 cloud:
  config:
   server:
    git:
     uri: file:///C:/proj_own/springCloud/GitCloud
     search-paths: 
      - config/conversion-service
      - config/exchange-service
server:
 port: 8888



