apiVersion: apps/v1
kind: Deployment
metadata:
 name: currency-conversion-service-deployment
 labels:
  app: currency-conversion-service-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: currency-conversion-service
 template:
  metadata:
   labels:
    app: currency-conversion-service
  spec:
   containers:
   - name: currency-conversion-service
     image: sandeshdhotre/currencyconversionservice
     ports:
     - name: mport
       containerPort: 9100
