apiVersion: apps/v1
kind: Deployment
metadata:
 name: currency-exchange-service-deployment
 labels:
  app: currency-exchange-service-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: currency-exchange-service
 template:
  metadata:
   labels:
    app: currency-exchange-service
  spec:
   containers:
   - name: currency-exchange-service
     image: sandeshdhotre/currencyexchangeservice
     ports:
     - name: mport
       containerPort: 9100
